FROM apache/airflow:2.9.3

USER root

# Install Java (needed by Spark) and download Spark.
RUN apt-get update && \
    apt-get install -y curl openjdk-11-jdk && \
    curl -L https://archive.apache.org/dist/spark/spark-3.5.1/spark-3.5.1-bin-hadoop3.tgz -o /tmp/spark.tgz && \
    tar -xzf /tmp/spark.tgz -C /opt && \
    ln -s /opt/spark-3.5.1-bin-hadoop3/bin/spark-submit /usr/local/bin/spark-submit && \
    rm /tmp/spark.tgz

USER airflow

